config/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import include, path, re_path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    re_path(r"^robots\.txt", include("robots.urls")),
    # path('pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path("", include(wagtail_urls)),
    prefix_default_language=False,
)

src/wagtailvideos/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path

from src.wagtailvideos.views import multiple, videos

app_name = "wagtailvideos"

urlpatterns = [
    path("add/", videos.add, name="add"),
    re_path(r"^usage/(\d+)/$", videos.usage, name="video_usage"),
    path("multiple/add/", multiple.add, name="add_multiple"),
    re_path(r"^multiple/(\d+)/delete/$", multiple.delete, name="delete_multiple"),
    re_path(r"^multiple/(\d+)/$", multiple.edit, name="edit_multiple"),
    re_path(r"^(\d+)/delete/$", videos.delete, name="delete"),
    re_path(r"^(\d+)/create_transcode/$", videos.create_transcode, name="create_transcode"),
    re_path(r"^(\d+)/$", videos.edit, name="edit"),
    path("", videos.index, name="index"),
]

src/wagtailvideos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.models import modelform_factory
from django.utils.translation import gettext as _
from enumchoicefield.forms import EnumField
from wagtail.admin import widgets
from wagtail.admin.forms.collections import BaseCollectionMemberForm, collection_member_permission_formset_factory

from src.wagtailvideos.fields import WagtailVideoField
from src.wagtailvideos.models import MediaFormats, Video, VideoQuality
from src.wagtailvideos.permissions import permission_policy as video_permission_policy


class BaseVideoForm(BaseCollectionMemberForm):
    permission_policy = video_permission_policy

    def __init__(self, *args, **kwargs):
        super(BaseVideoForm, self).__init__(*args, **kwargs)
        # A file is only required if there is not already a file, such as when
        # editing an existing video.  The file field is not used on the
        # multiple-upload forms, so may not be present
        if "file" in self.fields:
            self.fields["file"].required = "file" not in self.initial or not self.initial["file"]
            self.fields["file"].label = _("File")  # set field.label for file


# Callback to allow us to override the default form field for the video file field
def formfield_for_dbfield(db_field, **kwargs):
    # Check if this is the file field
    if db_field.name == "file":
        return WagtailVideoField(**kwargs)

    # For all other fields, just call its formfield() method.
    return db_field.formfield(**kwargs)


def get_video_form(model):
    fields = model.admin_form_fields
    if "collection" not in fields:
        # force addition of the 'collection' field, because leaving it out can
        # cause dubious results when multiple collections exist (e.g adding the
        # document to the root collection where the user may not have permission) -
        # and when only one collection exists, it will get hidden anyway.
        fields = list(fields) + ["collection"]

    return modelform_factory(
        model,
        form=BaseVideoForm,
        fields=fields,
        formfield_callback=formfield_for_dbfield,
        # set the 'file' widget to a FileInput rather than the default ClearableFileInput
        # so that when editing, we don't get the 'currently: ...' banner which is
        # a bit pointless here
        widgets={
            "tags": widgets.AdminTagWidget,
            "file": forms.FileInput(),
            "thumbnail": forms.FileInput(),
        },
    )


class VideoTranscodeAdminForm(forms.Form):
    media_format = EnumField(MediaFormats, label=_("Media format"))
    quality = EnumField(VideoQuality, label=_("Quality"))

    def __init__(self, video, data=None, **kwargs):
        super(VideoTranscodeAdminForm, self).__init__(data=data, **kwargs)
        self.video = video

    def save(self):
        media_format = self.cleaned_data["media_format"]
        quality = self.cleaned_data["quality"]
        self.video.do_transcode(media_format, quality)


GroupVideoPermissionFormSet = collection_member_permission_formset_factory(
    Video,
    [
        ("add_video", _("Add"), _("Add/edit videos you own")),
        ("change_video", _("Edit"), _("Edit any video")),
        ("choose_video", _("Choose"), _("Choose video")),
    ],
    "wagtailvideos/permissions/includes/video_permissions_formset.html",
)

src/wagtailvideos/views/chooser.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import View
from wagtail.admin.auth import PermissionPolicyChecker
from wagtail.admin.models import popular_tags_for_model
from wagtail.admin.views.generic.chooser import (
    BaseChooseView,
    ChooseResultsViewMixin,
    ChooseViewMixin,
    ChosenResponseMixin,
    ChosenViewMixin,
    CreateViewMixin,
    CreationFormMixin,
)
from wagtail.admin.viewsets.chooser import ChooserViewSet

from src.wagtailvideos import get_video_model
from src.wagtailvideos.forms import get_video_form
from src.wagtailvideos.permissions import permission_policy

permission_checker = PermissionPolicyChecker(permission_policy)


class VideoChosenResponseMixin(ChosenResponseMixin):
    def get_chosen_response_data(self, video):
        response_data = super().get_chosen_response_data(video)
        response_data["preview"] = {
            "url": video.thumbnail.url if video.thumbnail else "",
            "width": 165,
            "height": 165,
        }
        return response_data


class VideoCreationFormMixin(CreationFormMixin):
    creation_tab_id = "upload"
    create_action_label = _("Upload")
    create_action_clicked_label = _("Uploading…")
    permission_policy = permission_policy

    def get_creation_form_class(self):
        return get_video_form(self.model)

    def get_creation_form_kwargs(self):
        kwargs = super().get_creation_form_kwargs()
        if self.request.method in ("POST", "PUT"):
            kwargs["instance"] = self.model(uploaded_by_user=self.request.user)
        return kwargs


class BaseVideoChooseView(BaseChooseView):
    template_name = "wagtailvideos/chooser/chooser.html"
    results_template_name = "wagtailvideos/chooser/results.html"
    per_page = getattr(settings, "WAGTAILVIDEOS_CHOOSER_PAGE_SIZE", 12)
    ordering = "-created_at"

    def get_object_list(self):
        return permission_policy.instances_user_has_any_permission_for(self.request.user, ["choose"]).select_related(
            "collection",
        )

    def filter_object_list(self, objects):
        tag_name = self.request.GET.get("tag")
        if tag_name:
            objects = objects.filter(tags__name=tag_name)
        return super().filter_object_list(objects)

    def get_filter_form(self):
        FilterForm = self.get_filter_form_class()
        return FilterForm(self.request.GET, collections=self.collections)

    @cached_property
    def collections(self):
        collections = self.permission_policy.collections_user_has_permission_for(self.request.user, "choose")
        if len(collections) < 2:
            return None

        return collections

    def get(self, request):
        self.model = get_video_model()
        return super().get(request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "collections": self.collections,
            },
        )
        return context


class VideoChooseViewMixin(ChooseViewMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_tags"] = popular_tags_for_model(self.model)
        return context

    def get_response_json_data(self):
        json_data = super().get_response_json_data()
        json_data["tag_autocomplete_url"] = reverse("wagtailadmin_tag_autocomplete")
        return json_data


class VideoChooseView(VideoChooseViewMixin, VideoCreationFormMixin, BaseVideoChooseView):
    pass


class VideoChooseResultsView(ChooseResultsViewMixin, VideoCreationFormMixin, BaseVideoChooseView):
    pass


class VideoChosenView(ChosenViewMixin, VideoChosenResponseMixin, View):
    def get(self, request, *args, pk, **kwargs):
        self.model = get_video_model()
        return super().get(request, *args, pk, **kwargs)


class VideoUploadViewMixin(CreateViewMixin):
    def get(self, request):
        self.model = get_video_model()
        return super().get(request)

    def post(self, request):
        self.model = get_video_model()
        self.form = self.get_creation_form()

        if self.form.is_valid():
            image = self.save_form(self.form)

            # not specifying a format; return the image details now
            return self.get_chosen_response(image)

        else:  # form is invalid
            return self.get_reshow_creation_form_response()


class VideoUploadView(VideoUploadViewMixin, VideoCreationFormMixin, VideoChosenResponseMixin, View):
    pass


class VideoChooserViewSet(ChooserViewSet):
    choose_view_class = VideoChooseView
    choose_results_view_class = VideoChooseResultsView
    chosen_view_class = VideoChosenView
    create_view_class = VideoUploadView
    permission_policy = permission_policy
    register_widget = False

    icon = "media"
    choose_one_text = _("Choose a video")
    create_action_label = _("Upload")
    create_action_clicked_label = _("Uploading…")


viewset = VideoChooserViewSet(
    "wagtailvideos_chooser",
    model=get_video_model(),
    url_prefix="videos/chooser",
)

src/wagtailvideos/views/multiple.py
# -*- coding: utf-8 -*-
from distutils.version import LooseVersion

import wagtail
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.utils.encoding import force_str
from django.views.decorators.http import require_POST
from django.views.decorators.vary import vary_on_headers
from wagtail.search.backends import get_search_backends

from src.wagtailvideos import get_video_model
from src.wagtailvideos.forms import get_video_form
from src.wagtailvideos.permissions import permission_policy

if LooseVersion(wagtail.__version__) >= LooseVersion("2.7"):
    from wagtail.admin.auth import PermissionPolicyChecker
else:
    from wagtail.admin.utils import PermissionPolicyChecker

permission_checker = PermissionPolicyChecker(permission_policy)


def get_video_edit_form(VideoModel):
    VideoForm = get_video_form(VideoModel)

    # Make a new form with the file and focal point fields excluded
    class VideoEditForm(VideoForm):
        class Meta(VideoForm.Meta):
            model = VideoModel
            exclude = ("file",)

    return VideoEditForm


@vary_on_headers("X-Requested-With")
def add(request):
    Video = get_video_model()
    VideoForm = get_video_form(Video)

    collections = permission_policy.collections_user_has_permission_for(request.user, "add")
    if len(collections) > 1:
        collections_to_choose = collections
    else:
        # no need to show a collections chooser
        collections_to_choose = None

    if request.method == "POST":
        if request.headers.get("x-requested-with") != "XMLHttpRequest":
            return HttpResponseBadRequest("Cannot POST to this view without AJAX")

        if not request.FILES:
            return HttpResponseBadRequest("Must upload a file")

        # Build a form for validation
        form = VideoForm(
            {
                "title": request.FILES["files[]"].name,
                "collection": request.POST.get("collection"),
            },
            {
                "file": request.FILES["files[]"],
            },
        )
        if form.is_valid():
            # Save
            video = form.save(commit=False)
            video.uploaded_by_user = request.user
            video.save()

            # Success! Send back an edit form
            return JsonResponse(
                {
                    "success": True,
                    "video_id": int(video.id),
                    "form": render_to_string(
                        "wagtailvideos/multiple/edit_form.html",
                        {
                            "video": video,
                            "form": get_video_edit_form(Video)(instance=video, prefix="video-%d" % video.id),
                        },
                        request=request,
                    ),
                },
            )
        else:
            # Validation error
            return JsonResponse(
                {
                    "success": False,
                    # https://github.com/django/django/blob/stable/1.6.x/django/forms/util.py#L45
                    "error_message": "\n".join(["\n".join([force_str(i) for i in v]) for k, v in form.errors.items()]),
                },
            )
    else:
        form = VideoForm()

    return render(
        request,
        "wagtailvideos/multiple/add.html",
        {
            "max_filesize": form.fields["file"].max_upload_size,
            "help_text": form.fields["file"].help_text,
            "error_max_file_size": form.fields["file"].error_messages["file_too_large_unknown_size"],
            "error_accepted_file_types": form.fields["file"].error_messages["invalid_video_format"],
            "collections": collections_to_choose,
        },
    )


@require_POST
def edit(request, video_id, callback=None):
    Video = get_video_model()
    VideoForm = get_video_edit_form(Video)

    video = get_object_or_404(Video, id=video_id)

    if request.headers.get("x-requested-with") != "XMLHttpRequest":
        return HttpResponseBadRequest("Cannot POST to this view without AJAX")

    form = VideoForm(request.POST, request.FILES, instance=video, prefix="video-" + video_id)

    if form.is_valid():
        form.save()

        # Reindex the video to make sure all tags are indexed
        for backend in get_search_backends():
            backend.add(video)

        return JsonResponse(
            {
                "success": True,
                "video_id": int(video_id),
            },
        )
    else:
        return JsonResponse(
            {
                "success": False,
                "video_id": int(video_id),
                "form": render_to_string(
                    "wagtailvideos/multiple/edit_form.html",
                    {
                        "video": video,
                        "form": form,
                    },
                    request=request,
                ),
            },
        )


@require_POST
def delete(request, video_id):
    video = get_object_or_404(get_video_model(), id=video_id)

    if request.headers.get("x-requested-with") != "XMLHttpRequest":
        return HttpResponseBadRequest("Cannot POST to this view without AJAX")

    video.delete()

    return JsonResponse(
        {
            "success": True,
            "video_id": int(video_id),
        },
    )

src/wagtailvideos/templates/wagtailvideos/videos/_file_field_as_li.html
{% load wagtailadmin_tags %}
<li class="{% if field.field.required %}required{% endif %} {{ wrapper_classes }} {{ li_classes }} {% if field.errors %}error{% endif %}">
    {% include "wagtailvideos/videos/_file_field.html" %}
</li>

src/wagtailvideos/templates/wagtailvideos/videos/add.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Add a video" %}{% endblock %}

{% block extra_js %}
    {{ block.super }}

    {{ form.media.js }}

    {% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
    <script>
        $(function() {
            $('#id_tags').tagit({
                autocomplete: {source: "{{ autocomplete_url|addslashes }}"}
            });
        });
    </script>
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

{% block content %}
    {% trans "Add video" as add_str %}
    {% include "wagtailadmin/shared/header.html" with title=add_str icon="media" %}

    <div class="nice-padding">
        {% include "wagtailadmin/shared/non_field_errors.html" %}

        <form action="{% url 'wagtailvideos:add' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <ul class="fields">
                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% else %}
                        {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
                    {% endif %}
                {% endfor %}
                <li><input class="button" type="submit" value="{% trans 'Save' %}" /></li>
            </ul>
        </form>
    </div>
{% endblock %}

src/wagtailvideos/templates/wagtailvideos/videos/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailvideos_tags %}
{% load i18n %}
{% block titletag %}{% trans "Delete video" %}{% endblock %}

{% block content %}
    {% trans "Delete video" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str icon="media" %}

    <div class="row row-flush nice-padding">
        <div class="col6">
            {% video video controls style=max-width:100% %}
        </div>
        <div class="col6">
            <p>{% trans "Are you sure you want to delete this video?" %}</p>
            <form action="{% url 'wagtailvideos:delete' video.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" class="button serious" value="{% trans 'Yes, delete' %}" />
            </form>
        </div>
    </div>
{% endblock %}

src/wagtailvideos/templates/wagtailvideos/videos/edit.html
{% extends "wagtailadmin/base.html" %}

{% load static wagtailadmin_tags i18n wagtailvideos_tags %}

{% block titletag %}{% blocktrans with title=video.title %}Editing video {{ title }}{% endblocktrans %}{% endblock %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'wagtailvideos/css/edit-video.css' %}" type="text/css" /> {% endblock %}

{% block extra_js %}
{{ block.super }}
{% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
<script>
    {{ form.media.css }}
    $(function() {
        $('#id_tags').tagit({
            autocomplete: {
                source: "{{ autocomplete_url|addslashes }}"
            }
        });
    });
</script>
{% endblock %}
{% block content %}
{% trans "Editing" as editing_str %}

{% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=video.title icon="media" %}

<div class="row row-flush nice-padding">
    <div class="col6">
        <form action="{% url 'wagtailvideos:edit' video.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <ul class="fields">
                {% for field in form %}
                  {% if field.name == 'file' %}
                    {% include "wagtailvideos/videos/_file_field_as_li.html"  with li_classes="label-above label-uppercase" %}
                  {% elif field.is_hidden %}
                    {{ field }}
                  {% else %}
                    {% include "wagtailadmin/shared/field_as_li.html" with li_classes="label-above label-uppercase" %}
                  {% endif %}
                {% endfor %}
                <li>
                    <input type="submit" class="button" value="{% trans 'Save' %}" />
                    {% if user_can_delete %}
                        <a href="{% url 'wagtailvideos:delete' video.id %}" class="button button-secondary no">{% trans "Delete video" %}</a>
                    {% endif %}
                </li>
            </ul>
        </form>
    </div>
    <div class="col6">
        <div class="row">
            <div class="col10 divider-after">
                {% video video controls style=max-width:100%;width:100%;height:auto; %}
            </div>
            <div class="col2">
                <dl style="margin-top: 0;">
                    {% if video.thumbnail %}
                    <dt>{% trans "Thumbnail" %}</dt>
                    <dd><img src="{{ video.thumbnail.url }}" alt="{% trans 'Video thumbnail' %}" /></dd>
                    {% endif %}
                    <dt>{% trans "Filesize" %}</dt>
                    <dd>{% if filesize %}{{ filesize|filesizeformat }}{% else %}{% trans "File not found" %}{% endif %}</dd>
                    {% if video.duration %}
                    <dt>{% trans "Duration" %}</dt>
                    <dd>{{ video.formatted_duration }}</dd>
                    {% endif %}
                    <dt>{% trans "Usage" %}</dt>
                    <dd>
                        <a href="{{ video.usage_url }}">{% blocktrans count usage_count=video.get_usage.count %}Used {{ usage_count }} time{% plural %}Used {{ usage_count }} times{% endblocktrans %}</a>
                    </dd>
                </dl>
            </div>
        </div>
        <div class="row" style="margin-top: 2em;">
        {% if can_transcode %}
            <h2 class="u-text-transform-uppercase">{% trans "Transcodes" %}</h2>
            <p>{% trans "If you wish to generate HTML5 compliant transcodes use the form below. This may take a while depending on the length of the video." %}</p>
            {% if transcodes %}
            <h3 class="u-text-transform-uppercase">{% trans "Available Transcodes" %}</h3>
            <ul>
                {% for transcode in transcodes %}
                <li>
                    {% blocktrans with media_format=transcode.media_format quality=transcode.quality %}{{ media_format }} ({{ quality }} quality){% endblocktrans %}
                    {% if transcode.processing %}
                        <span class="processing">{% trans "(Processing... hold tight)" %} </span>
                    {% endif %}
                    {% if transcode.error_message %}
                        <span class="transcode-error">{% trans "ERROR:" %}</span>
                        <div class="transcode-error">
                            <pre> {{ transcode.error_message }}</pre>
                        </div>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <h3 class="u-text-transform-uppercase">{% trans "Create transcode" %}</h3>
            <form action="{% url 'wagtailvideos:create_transcode' video.id %}" method="POST">
                <ul class="fields">
                    {% csrf_token %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=transcode_form.media_format li_classes="label-above label-uppercase" %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=transcode_form.quality li_classes="label-above label-uppercase" %}
                    <li>
                        <input class="button" type="submit" value="{% trans 'Start' %}" />
                    </li>
                </ul>
            </form>
        {% else %}
            <br/><br/>
            <span class="transcode-error">{% trans "Ffmpeg is not found on your server or you have disabled transcodes. Please install Ffmepg and make sure that transcoding is enabled if you wish to transcode videos into an HTML5 video compliant format." %}</span>
        {% endif %}
        {% if tracks_action_url %}
            <h2 class="u-text-transform-uppercase">{% trans "Tracks" %}</h2>
            <p>{% trans 'You can add/edit subtitles or accessibility captions for this video. For information about the filetype that should be used see the mozilla docs on <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API">WebVTT</a>' %}</p>
                {% if video.track_listing %}
                <ul>
                {% for track in video.track_listing.tracks.all %}
                    <li>{{ track }}</li>
                {% endfor %}
                </ul>
                <a class="button" href="{{ tracks_action_url }}">{% trans "Edit" %}</a>
                {% else %}
                <a class="button" href="{{ tracks_action_url }}">{% trans "Add tracks" %}</a>
                {% endif %}
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

src/wagtailvideos/templates/wagtailvideos/videos/index.html
{% extends "wagtailadmin/base.html" %}
{% load wagtailadmin_tags %}
{% load i18n %}

{% block titletag %}{% trans "Videos" %}{% endblock %}
{% block extra_js %}
    {{ block.super }}
    <script>
        window.headerSearch = {
            url: "{% url 'wagtailvideos:index' %}",
            termInput: "#id_q",
            targetOutput: "#image-results"
        }

        $(function() {
            $('#collection_chooser_collection_id').change(function() {
                this.form.submit();
            })
        });
    </script>
{% endblock %}

{% block content %}
    {% trans "Videos" as im_str %}
    {% url 'wagtailvideos:listing_results' as search_results_url %}
    {% trans "Add an video" as add_img_str %}
    {% url "wagtailvideos:add_multiple" as add_link %}
    {% querystring as querystring %}
    {% include "wagtailadmin/shared/header.html" with title=im_str action_url=add_link|add:querystring icon="media" action_text=add_img_str search_url="wagtailvideos:index" search_results_url=search_results_url search_target="#image-results" %}


    <div class="nice-padding">
        <form class="image-search" action="{% url 'wagtailvideos:index' %}" method="GET" novalidate>
            {% if current_tag %}
                <input type="hidden" name="tag" value="{{ current_tag }}" />
            {% endif %}

            {% field_row max_content=True %}
                {% if collections %}
                    {% include "wagtailadmin/shared/collection_chooser.html" %}
                {% endif %}

                {% trans "Sort by" as sort_by %}
                {% field label_text=sort_by id_for_label="order_images_by" %}
                    <select id="order_images_by" name="ordering" data-controller="w-submit" data-action="change->w-submit#submit">
                        {% for ordering, ordering_text in ORDERING_OPTIONS.items %}
                            <option value="{{ ordering }}" {% if current_ordering == ordering %}selected="selected"{% endif %}>{{ ordering_text }}</option>
                        {% endfor %}
                    </select>
                {% endfield %}

                {% trans "Entries per page" as entries_per_page_label %}
                {% field label_text=entries_per_page_label id_for_label="entries_per_page_label" %}
                    <select id="entries_per_page" name="entries_per_page" data-controller="w-submit" data-action="change->w-submit#submit">
                        {% for value in ENTRIES_PER_PAGE_CHOICES %}
                            <option value="{{ value }}" {% if entries_per_page == value %}selected="selected"{% endif %}>{{ value }}</option>
                        {% endfor %}
                    </select>
                {% endfield %}
            {% endfield_row %}

            {% if popular_tags %}
                <fieldset class="tagfilter">
                    <legend>{% trans 'Popular Tags:' %}</legend>
                    {% for tag in popular_tags %}
                        {% if tag.name != current_tag %}
                            <a class="button button-small button-secondary bicolor button--icon" href="{% url 'wagtailvideos:index' %}{% querystring tag=tag.name %}">{% icon name="tag" wrapped=1 %}{{ tag.name }}</a>
                        {% else %}
                            <a class="button button-small bicolor button--icon" href="{% url 'wagtailvideos:index' %}{% querystring tag=tag.name %}">{% icon name="tag" wrapped=1 %}{{ tag.name }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if current_tag %}
                        <a class="button button-small bicolor button-secondary button--icon" href="{% url 'wagtailvideos:index' %}{% querystring tag='' %}">{% icon name="cross" wrapped=1 %}{% trans 'Clear' %}</a>
                    {% endif %}
                </fieldset>
            {% endif %}
        </form>

        <div id="image-results">
            {% include "wagtailvideos/videos/results.html" with querystring=querystring %}
        </div>
        {% trans "Select all images in listing" as select_all_text %}
        {% include 'wagtailadmin/bulk_actions/footer.html' with select_all_obj_text=select_all_text app_label=app_label model_name=model_name objects=images parent=current_collection.id %}
    </div>

{% endblock %}

src/wagtailvideos/templates/wagtailvideos/videos/results.html
{% load wagtailadmin_tags %}
{% load i18n %}
{% if videos %}
    {% if is_searching %}
        <h2>
        {% blocktrans count counter=videos.paginator.count %}
            There is one match
        {% plural %}
            There are {{ counter }} matches
        {% endblocktrans %}
        </h2>

        {% search_other %}
    {% else %}
        <h2>{% trans "Latest videos" %}</h2>
    {% endif %}

    <ul class="listing horiz images">
        {% for video in videos %}
            <li>
                <a class="image-choice" href="{% url 'wagtailvideos:edit' video.id %}">
                    <figure>
                        {% if video.thumbnail %}
                            <img src="{{ video.thumbnail.url }}" height="165" width="165" class="show-transparency" alt="{% trans 'Video thumbnail' %}"/>
                        {% else %}
                            <img width="165" height="165" class="show-transparency" alt="" />
                        {% endif %}
                        <figcaption>{{ video.title|ellipsistrim:60 }}</figcaption>
                    </figure>
                </a>
            </li>
        {% endfor %}
    </ul>

    {% include "wagtailadmin/shared/pagination_nav.html" with items=videos is_searching=is_searching query_string=query_string linkurl="wagtailvideos:index" %}

{% else %}
    {% if is_searching %}
        <h2>{% blocktrans %}Sorry, no videos match "<em>{{ query_string }}</em>"{% endblocktrans %}</h2>

        {% search_other %}
    {% else %}
        {% url 'wagtailvideos:add_multiple' as wagtailvideos_add_video_url %}
        {% if current_collection %}
            <p>{% blocktrans %}You've not uploaded any videos in this collection. Why not <a href="{{ wagtailvideos_add_video_url }}">add one now</a>?{% endblocktrans %}</p>
        {% else %}
            <p>{% blocktrans %}You've not uploaded any videos. Why not <a href="{{ wagtailvideos_add_video_url }}">add one now</a>?{% endblocktrans %}</p>
        {% endif %}
    {% endif %}
{% endif %}