config/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.urls import include, path, re_path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    # path("admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    re_path(r"^robots\.txt", include("robots.urls")),
    # path('pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path("", include(wagtail_urls)),
    prefix_default_language=False,
)

src/wagtailvideos/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path

from src.wagtailvideos.views import multiple, videos

app_name = "wagtailvideos"

urlpatterns = [
    path("add/", videos.add, name="add"),
    re_path(r"^usage/(\d+)/$", videos.usage, name="video_usage"),
    path("multiple/add/", multiple.add, name="add_multiple"),
    re_path(r"^multiple/(\d+)/delete/$", multiple.delete, name="delete_multiple"),
    re_path(r"^multiple/(\d+)/$", multiple.edit, name="edit_multiple"),
    re_path(r"^(\d+)/delete/$", videos.delete, name="delete"),
    re_path(r"^(\d+)/create_transcode/$", videos.create_transcode, name="create_transcode"),
    re_path(r"^(\d+)/$", videos.edit, name="edit"),
    path("", videos.index, name="index"),
]

src/wagtailvideos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.models import modelform_factory
from django.utils.translation import gettext as _
from enumchoicefield.forms import EnumField
from wagtail.admin import widgets
from wagtail.admin.forms.collections import BaseCollectionMemberForm, collection_member_permission_formset_factory

from src.wagtailvideos.fields import WagtailVideoField
from src.wagtailvideos.models import MediaFormats, Video, VideoQuality
from src.wagtailvideos.permissions import permission_policy as video_permission_policy


class BaseVideoForm(BaseCollectionMemberForm):
    permission_policy = video_permission_policy

    def __init__(self, *args, **kwargs):
        super(BaseVideoForm, self).__init__(*args, **kwargs)
        # A file is only required if there is not already a file, such as when
        # editing an existing video.  The file field is not used on the
        # multiple-upload forms, so may not be present
        if "file" in self.fields:
            self.fields["file"].required = "file" not in self.initial or not self.initial["file"]
            self.fields["file"].label = _("File")  # set field.label for file


# Callback to allow us to override the default form field for the video file field
def formfield_for_dbfield(db_field, **kwargs):
    # Check if this is the file field
    if db_field.name == "file":
        return WagtailVideoField(**kwargs)

    # For all other fields, just call its formfield() method.
    return db_field.formfield(**kwargs)


def get_video_form(model):
    fields = model.admin_form_fields
    if "collection" not in fields:
        # force addition of the 'collection' field, because leaving it out can
        # cause dubious results when multiple collections exist (e.g adding the
        # document to the root collection where the user may not have permission) -
        # and when only one collection exists, it will get hidden anyway.
        fields = list(fields) + ["collection"]

    return modelform_factory(
        model,
        form=BaseVideoForm,
        fields=fields,
        formfield_callback=formfield_for_dbfield,
        # set the 'file' widget to a FileInput rather than the default ClearableFileInput
        # so that when editing, we don't get the 'currently: ...' banner which is
        # a bit pointless here
        widgets={
            "tags": widgets.AdminTagWidget,
            "file": forms.FileInput(),
            "thumbnail": forms.FileInput(),
        },
    )


class VideoTranscodeAdminForm(forms.Form):
    media_format = EnumField(MediaFormats, label=_("Media format"))
    quality = EnumField(VideoQuality, label=_("Quality"))

    def __init__(self, video, data=None, **kwargs):
        super(VideoTranscodeAdminForm, self).__init__(data=data, **kwargs)
        self.video = video

    def save(self):
        media_format = self.cleaned_data["media_format"]
        quality = self.cleaned_data["quality"]
        self.video.do_transcode(media_format, quality)


GroupVideoPermissionFormSet = collection_member_permission_formset_factory(
    Video,
    [
        ("add_video", _("Add"), _("Add/edit videos you own")),
        ("change_video", _("Edit"), _("Edit any video")),
        ("choose_video", _("Choose"), _("Choose video")),
    ],
    "wagtailvideos/permissions/includes/video_permissions_formset.html",
)

src/wagtailvideos/views/chooser.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django.views.generic.base import View
from wagtail.admin.auth import PermissionPolicyChecker
from wagtail.admin.models import popular_tags_for_model
from wagtail.admin.views.generic.chooser import (
    BaseChooseView,
    ChooseResultsViewMixin,
    ChooseViewMixin,
    ChosenResponseMixin,
    ChosenViewMixin,
    CreateViewMixin,
    CreationFormMixin,
)
from wagtail.admin.viewsets.chooser import ChooserViewSet

from src.wagtailvideos import get_video_model
from src.wagtailvideos.forms import get_video_form
from src.wagtailvideos.permissions import permission_policy

permission_checker = PermissionPolicyChecker(permission_policy)


class VideoChosenResponseMixin(ChosenResponseMixin):
    def get_chosen_response_data(self, video):
        response_data = super().get_chosen_response_data(video)
        response_data["preview"] = {
            "url": video.thumbnail.url if video.thumbnail else "",
            "width": 165,
            "height": 165,
        }
        return response_data


class VideoCreationFormMixin(CreationFormMixin):
    creation_tab_id = "upload"
    create_action_label = _("Upload")
    create_action_clicked_label = _("Uploading…")
    permission_policy = permission_policy

    def get_creation_form_class(self):
        return get_video_form(self.model)

    def get_creation_form_kwargs(self):
        kwargs = super().get_creation_form_kwargs()
        if self.request.method in ("POST", "PUT"):
            kwargs["instance"] = self.model(uploaded_by_user=self.request.user)
        return kwargs


class BaseVideoChooseView(BaseChooseView):
    template_name = "wagtailvideos/chooser/chooser.html"
    results_template_name = "wagtailvideos/chooser/results.html"
    per_page = getattr(settings, "WAGTAILVIDEOS_CHOOSER_PAGE_SIZE", 12)
    ordering = "-created_at"

    def get_object_list(self):
        return permission_policy.instances_user_has_any_permission_for(self.request.user, ["choose"]).select_related(
            "collection",
        )

    def filter_object_list(self, objects):
        tag_name = self.request.GET.get("tag")
        if tag_name:
            objects = objects.filter(tags__name=tag_name)
        return super().filter_object_list(objects)

    def get_filter_form(self):
        FilterForm = self.get_filter_form_class()
        return FilterForm(self.request.GET, collections=self.collections)

    @cached_property
    def collections(self):
        collections = self.permission_policy.collections_user_has_permission_for(self.request.user, "choose")
        if len(collections) < 2:
            return None

        return collections

    def get(self, request):
        self.model = get_video_model()
        return super().get(request)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "collections": self.collections,
            },
        )
        return context


class VideoChooseViewMixin(ChooseViewMixin):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["popular_tags"] = popular_tags_for_model(self.model)
        return context

    def get_response_json_data(self):
        json_data = super().get_response_json_data()
        json_data["tag_autocomplete_url"] = reverse("wagtailadmin_tag_autocomplete")
        return json_data


class VideoChooseView(VideoChooseViewMixin, VideoCreationFormMixin, BaseVideoChooseView):
    pass


class VideoChooseResultsView(ChooseResultsViewMixin, VideoCreationFormMixin, BaseVideoChooseView):
    pass


class VideoChosenView(ChosenViewMixin, VideoChosenResponseMixin, View):
    def get(self, request, *args, pk, **kwargs):
        self.model = get_video_model()
        return super().get(request, *args, pk, **kwargs)


class VideoUploadViewMixin(CreateViewMixin):
    def get(self, request):
        self.model = get_video_model()
        return super().get(request)

    def post(self, request):
        self.model = get_video_model()
        self.form = self.get_creation_form()

        if self.form.is_valid():
            image = self.save_form(self.form)

            # not specifying a format; return the image details now
            return self.get_chosen_response(image)

        else:  # form is invalid
            return self.get_reshow_creation_form_response()


class VideoUploadView(VideoUploadViewMixin, VideoCreationFormMixin, VideoChosenResponseMixin, View):
    pass


class VideoChooserViewSet(ChooserViewSet):
    choose_view_class = VideoChooseView
    choose_results_view_class = VideoChooseResultsView
    chosen_view_class = VideoChosenView
    create_view_class = VideoUploadView
    permission_policy = permission_policy
    register_widget = False

    icon = "media"
    choose_one_text = _("Choose a video")
    create_action_label = _("Upload")
    create_action_clicked_label = _("Uploading…")


viewset = VideoChooserViewSet(
    "wagtailvideos_chooser",
    model=get_video_model(),
    url_prefix="videos/chooser",
)

src/wagtailvideos/views/multiple.py
# -*- coding: utf-8 -*-
from distutils.version import LooseVersion

import wagtail
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.utils.encoding import force_str
from django.views.decorators.http import require_POST
from django.views.decorators.vary import vary_on_headers
from wagtail.search.backends import get_search_backends

from src.wagtailvideos import get_video_model
from src.wagtailvideos.forms import get_video_form
from src.wagtailvideos.permissions import permission_policy

if LooseVersion(wagtail.__version__) >= LooseVersion("2.7"):
    from wagtail.admin.auth import PermissionPolicyChecker
else:
    from wagtail.admin.utils import PermissionPolicyChecker

permission_checker = PermissionPolicyChecker(permission_policy)


def get_video_edit_form(VideoModel):
    VideoForm = get_video_form(VideoModel)

    # Make a new form with the file and focal point fields excluded
    class VideoEditForm(VideoForm):
        class Meta(VideoForm.Meta):
            model = VideoModel
            exclude = ("file",)

    return VideoEditForm


@vary_on_headers("X-Requested-With")
def add(request):
    Video = get_video_model()
    VideoForm = get_video_form(Video)

    collections = permission_policy.collections_user_has_permission_for(request.user, "add")
    if len(collections) > 1:
        collections_to_choose = collections
    else:
        # no need to show a collections chooser
        collections_to_choose = None

    if request.method == "POST":
        if request.headers.get("x-requested-with") != "XMLHttpRequest":
            return HttpResponseBadRequest("Cannot POST to this view without AJAX")

        if not request.FILES:
            return HttpResponseBadRequest("Must upload a file")

        # Build a form for validation
        form = VideoForm(
            {
                "title": request.FILES["files[]"].name,
                "collection": request.POST.get("collection"),
            },
            {
                "file": request.FILES["files[]"],
            },
        )
        if form.is_valid():
            # Save
            video = form.save(commit=False)
            video.uploaded_by_user = request.user
            video.save()

            # Success! Send back an edit form
            return JsonResponse(
                {
                    "success": True,
                    "video_id": int(video.id),
                    "form": render_to_string(
                        "wagtailvideos/multiple/edit_form.html",
                        {
                            "video": video,
                            "form": get_video_edit_form(Video)(instance=video, prefix="video-%d" % video.id),
                        },
                        request=request,
                    ),
                },
            )
        else:
            # Validation error
            return JsonResponse(
                {
                    "success": False,
                    # https://github.com/django/django/blob/stable/1.6.x/django/forms/util.py#L45
                    "error_message": "\n".join(["\n".join([force_str(i) for i in v]) for k, v in form.errors.items()]),
                },
            )
    else:
        form = VideoForm()

    return render(
        request,
        "wagtailvideos/multiple/add.html",
        {
            "max_filesize": form.fields["file"].max_upload_size,
            "help_text": form.fields["file"].help_text,
            "error_max_file_size": form.fields["file"].error_messages["file_too_large_unknown_size"],
            "error_accepted_file_types": form.fields["file"].error_messages["invalid_video_format"],
            "collections": collections_to_choose,
        },
    )


@require_POST
def edit(request, video_id, callback=None):
    Video = get_video_model()
    VideoForm = get_video_edit_form(Video)

    video = get_object_or_404(Video, id=video_id)

    if request.headers.get("x-requested-with") != "XMLHttpRequest":
        return HttpResponseBadRequest("Cannot POST to this view without AJAX")

    form = VideoForm(request.POST, request.FILES, instance=video, prefix="video-" + video_id)

    if form.is_valid():
        form.save()

        # Reindex the video to make sure all tags are indexed
        for backend in get_search_backends():
            backend.add(video)

        return JsonResponse(
            {
                "success": True,
                "video_id": int(video_id),
            },
        )
    else:
        return JsonResponse(
            {
                "success": False,
                "video_id": int(video_id),
                "form": render_to_string(
                    "wagtailvideos/multiple/edit_form.html",
                    {
                        "video": video,
                        "form": form,
                    },
                    request=request,
                ),
            },
        )


@require_POST
def delete(request, video_id):
    video = get_object_or_404(get_video_model(), id=video_id)

    if request.headers.get("x-requested-with") != "XMLHttpRequest":
        return HttpResponseBadRequest("Cannot POST to this view without AJAX")

    video.delete()

    return JsonResponse(
        {
            "success": True,
            "video_id": int(video_id),
        },
    )

src/wagtailvideos/templates/wagtailvideos/multiple/add.html
{% extends "wagtailadmin/base.html" %}
{% load i18n static wagtailadmin_tags %}
{% block titletag %}{% trans "Add multiple videos" %}{% endblock %}
{% block extra_css %}
    {{ block.super }}

    {{ form_media.css }}
{% endblock %}


{% block content %}
    {% trans "Add videos" as add_str %}
    {% include "wagtailadmin/shared/header.html" with title=add_str icon="media" %}
    <div class="nice-padding">
        <div class="drop-zone">
            <p>{% trans "Drag and drop videos into this area to upload immediately." %}</p>
            <p>{{ help_text }}</p>

            <form action="{% url 'wagtailvideos:add_multiple' %}" method="POST" enctype="multipart/form-data">
                <div class="replace-file-input">
                    <button class="button bicolor icon icon-plus">{% trans "Or choose from your computer" %}</button>
                    <input id="fileupload" type="file" name="files[]" data-url="{% url 'wagtailvideos:add_multiple' %}" multiple>
                </div>
                {% csrf_token %}
                {% if collections %}
                    <div class="field">
                        <label for="id_addvideo_collection">{% trans "Add to collection:" %}</label>
                        <div class="field-content">
                            <select id="id_addvideo_collection" name="collection">
                                {% for collection in collections %}
                                    <option value="{{ collection.id }}">{{ collection.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                {% endif %}
            </form>
        </div>

        <div id="overall-progress" class="progress progress-secondary">
            <div class="bar" style="width: 0%;">0%</div>
        </div>

        <ul id="upload-list" class="upload-list multiple"></ul>
    </div>

    <script id="upload-list-item" type="text/template">
        <li class="row">
            <div class="left col3">
                <div class="preview">
                    <div class="progress">
                        <div class="bar" style="width: 0%;"></div>
                    </div>
                </div>
            </div>
            <div class="right col9">
                <p class="status-msg success">{% trans "Upload successful. Please update this video with a more appropriate title, if necessary. You may also delete the video completely if the upload wasn't required." %}</p>
                <p class="status-msg failure">{% trans "Sorry, upload failed." %}</p>
                <p class="status-msg update-success">{% trans "Video updated." %}</p>
                <p class="status-msg failure error_messages"></p>
            </div>
        </li>
    </script>
{% endblock %}

{% block extra_js %}
    {{ block.super }}

    {{ form_media.js }}
    <!-- this exact order of plugins is vital -->
    <script src="{% versioned_static 'wagtailimages/js/vendor/load-image.min.js' %}"></script>
    <script src="{% versioned_static 'wagtailimages/js/vendor/canvas-to-blob.min.js' %}"></script>
    <script src="{% versioned_static 'wagtailadmin/js/vendor/jquery.iframe-transport.js' %}"></script>
    <script src="{% versioned_static 'wagtailadmin/js/vendor/jquery.fileupload.js' %}"></script>
    <script src="{% versioned_static 'wagtailadmin/js/vendor/jquery.fileupload-process.js' %}"></script>
    <script src="{% versioned_static 'wagtailimages/js/vendor/jquery.fileupload-image.js' %}"></script>
    <script src="{% versioned_static 'wagtailimages/js/vendor/jquery.fileupload-validate.js' %}"></script>
    <script src="{% versioned_static 'wagtailadmin/js/vendor/tag-it.js' %}"></script>

    <!-- Main script -->
    <script src="{% static 'wagtailvideos/js/add-multiple.js' %}"></script>

    {% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
    <script>
        window.fileupload_opts = {
            simple_upload_url: "{% url 'wagtailvideos:add' %}",
            max_file_size: {{ max_filesize|stringformat:"s"|default:"null" }}, //numeric format
            errormessages: {
                max_file_size: "{{ error_max_file_size }}",
                accepted_file_types: "{{ error_accepted_file_types }}"
            }
        };
        window.tagit_opts = {
            autocomplete: {source: "{{ autocomplete_url|addslashes }}"}
        };
    </script>
{% endblock %}

src/wagtailvideos/templates/wagtailvideos/multiple/edit_form.html
{% load i18n %}
{% load wagtailadmin_tags %}
<form action="{% url 'wagtailvideos:edit_multiple' video.id %}" method="POST" enctype="multipart/form-data">
    <ul class="fields">
        {% csrf_token %}
        {% for field in form %}
            {% if field.is_hidden %}
                {{ field }}
            {% else %}
                {% include "wagtailadmin/shared/field_as_li.html" %}
            {% endif %}
        {% endfor %}
        <li>
            <input class="button" type="submit" value="{% trans 'Update' %}" />
            <a href="{% url 'wagtailvideos:delete_multiple' video.id %}" class="delete button button-secondary no">{% trans "Delete" %}</a>
        </li>
    </ul>
</form>
<div data-video-thumb="{{ video.id }}" class="thumb icon icon-media hasthumb">
    {% if video.thumbnail %}
    <img src="{{ video.thumbnail.url }}" alt="{% trans 'Video thumbnail' %}" />
    {% endif %}
</div>
<script>
    var thumb = $("[data-video-thumb=\"" + {{ video.id }} + "\"]");
    $("[data-thumb-target=\"" + {{ video.id }} + "\"]").append(thumb);
</script>